services:
  unifi-geth:
    build:
      context: .
      dockerfile: Dockerfile.unifi-geth
    container_name: unifi-geth
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
    volumes:
      - ./data/unifi-geth:/app/data/unifi-geth
    networks:
      - unifi-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  contract-deployer:
    build:
      context: .
      dockerfile: Dockerfile.contract-deployer
    container_name: contract-deployer
    volumes:
      - contract-data:/app/data
    networks:
      - unifi-network
    depends_on:
      - unifi-geth
    extra_hosts:
      - "host.docker.internal:host-gateway"

  taiko-driver:
    build:
      context: .
      dockerfile: Dockerfile.taiko-client
    container_name: taiko-driver
    command: ["driver"]
    networks:
      - unifi-network
    volumes:
      - contract-data:/app/data
    depends_on:
      - contract-deployer
    extra_hosts:
      - "host.docker.internal:host-gateway"

  taiko-proposer:
    build:
      context: .
      dockerfile: Dockerfile.taiko-client
    container_name: taiko-proposer
    command: ["proposer"]
    networks:
      - unifi-network
    volumes:
      - contract-data:/app/data
    depends_on:
      - contract-deployer
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  unifi-network:
    driver: bridge

volumes:
  contract-data:
